
[Interface]
PrivateKey = E4sOO4byyl1RmaVjvsxeEuFRsj4qZCv7/QuaTA3IhCs=
Address = fdaa:0:36d7:a7b:e23:0:a:2/120
DNS = fdaa:0:36d7::3

[Peer]
PublicKey = BKj9TkkhUgz9rCeNcqz2X2A/ZzABgY0SJ+gYt8DrCSc=
AllowedIPs = fdaa:0:36d7::/48
Endpoint = sin1.gateway.6pn.dev:51820
PersistentKeepalive = 15

